#!/bin/bash
# Bumps the version string in action/VERSION, creating a annotated tag for the new
# version and a commit for action/VERSION.

set -euo pipefail

current_version="`cat action/VERSION`"
version_type="$1"

$VIRTUAL_ENV/bin/bump2version --current-version $current_version --tag --commit $version_type action/VERSION
